### ISSUE TITLE
errors logs

### ISSUE THREAD

**Issue by kleuser75** [stevotvr/sourcemod-vacbans#1]
[SM] Exception reported: Client index 9 is invalid (arg 3)
[SM] Blaming: vacbans.smx
[SM] Call stack trace:
[SM]   [0] LogToFile
[SM]   [1] Line 826, D:\Dev\sm110\scripting\vacbans.sp::ConnectToApi
[SM]   [2] Line 812, D:\Dev\sm110\scripting\vacbans.sp::OnQueryPlayerLookup
Error log file session closed.

SM 1.10.0.6387
Plugin version 2.3.0

**Comment by stevotvr** [comment]
This should only happened when the plugin is compiled with debug mode enabled. I'll get it fixed.

**Comment by stevotvr** [comment]
It should be fixed now.
