### ISSUE TITLE
Playername wrong

### ISSUE THREAD

**Issue by Styla84** [stevotvr/sourcemod-vacbans#2]
After ban, in vacbans.log. Name unreadable.
`L 04/06/2019 - 21:11:17: [vacbans.smx] ðšœðš•ðš’ðš—<28><STEAM_1:0:XXXXXXX><> VAC bans: 0, Game bans: 1, Community: CLEAN, Economy: CLEAN`

In Sourcebans, the name is displayed as ??????????????.

Counter-Strike Global Offensive
Plugin Version 2.3.0
Sourcemod Version Up to Date

**Comment by stevotvr** [comment]
Looks like a multibyte character encoding issue. I will look into it. Thanks and sorry for the delayed response.

**Comment by stevotvr** [comment]
I looked into it and I don't think anything can be done about this from the plugin. SourceMod handles printing the name.
