### ISSUE TITLE
[Feature Request] Native Forwards for using with other plugins

### ISSUE THREAD

**Issue by TandelK** [stevotvr/sourcemod-vacbans#3]
It will be a great feature to have natives forwards allowing other plugins to check VAC status using your Forwards. Will allow most of the Bans plugin also to automatically check for VAC Status

**Comment by stevotvr** [comment]
That sounds like a good idea. I've never written a forward before, so I'll have to learn how to do that. Thanks for the suggestion!

**Comment by stevotvr** [comment]
#4

**Comment by stevotvr** [comment]
It's been added. See #4

**Comment by TandelK** [comment]
The reason why i made this request because the original person who actually  did Native Forward is making a plugin of RankMe for CSGO and we have lot of VAC Ban IDs inside the Rank table and wanted to really get info for deleting VAC Ban ids from time to time. Instead of writing complete new plugin for checking Rank i found your plugin usefull so just went ahead and created a request and also gave the reference to @rogeraabbccdd about this.

**Comment by stevotvr** [comment]
Cool. I hope the new forward is useful.
